/* roundabout_priority_tree.h — fixed embedded API for car4 roundabout detection.
 * Generated by scripts/35_gen_c.py — do not edit by hand.
 * C251 适配: <stdint.h> 不存在, 改用项目 zf_common_typedef.h (uint8/uint16 已定义, 无需 typedef 别名)
 *
 *   uint8 roundabout_priority_tree_predict(uint16 CH1, uint16 CH2, uint16 CH3,
 *                                          uint16 CH4, uint16 TOF);
 *   returns 1 = roundabout (环岛), 0 = non-roundabout (非环岛)
 *
 * Model: ensemble of complete shallow decision trees (per-file K and depth),
 *        INT8 leaf weights, uint8 feature thresholds, integer accumulation.
 * Feature quantization (done inside the function):
 *   CH1..CH4 -> clamp to 255 (identity grid); TOF -> round(TOF/32) clamp 255
 *   plus 5 derived channels (differences/sums), see body.
 */
#ifndef ROUNDABOUT_PRIORITY_TREE_H
#define ROUNDABOUT_PRIORITY_TREE_H

#include "zf_common_typedef.h"

uint8 roundabout_priority_tree_predict(uint16 CH1, uint16 CH2, uint16 CH3,
                                       uint16 CH4, uint16 TOF);

#endif /* ROUNDABOUT_PRIORITY_TREE_H */
